# Generated by Django 3.1.7 on 2021-05-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timefield',
            name='timeStamFfield',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cowry.idfield'),
        ),
    ]
