# Generated by Django 3.1.7 on 2021-05-23 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cowry', '0002_auto_20210523_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='unique_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uu_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('timeStamFfield', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='timefield',
            name='timeStamFfield',
        ),
        migrations.DeleteModel(
            name='idField',
        ),
        migrations.DeleteModel(
            name='timefield',
        ),
    ]
