# Generated by Django 3.1.7 on 2021-05-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowry', '0003_auto_20210523_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unique_field',
            old_name='timeStamFfield',
            new_name='timeStampFfield',
        ),
    ]
