# Generated by Django 3.1.7 on 2021-05-24 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowry', '0005_auto_20210524_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unique_field',
            name='timeStampField',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
