# Generated by Django 3.1.7 on 2021-05-24 02:28

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cowry', '0007_auto_20210524_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='testP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timed', models.DateTimeField(default=datetime.datetime, verbose_name=uuid.UUID('ce7b22f5-e6bd-4b19-b9e1-587fc664c6a4'))),
            ],
        ),
    ]
