# Generated by Django 3.1.7 on 2021-05-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowry', '0008_testp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testP',
        ),
    ]
